image:
  name: docker/compose:1.24.1
  entrypoint: [""]

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

build:
  stage: build
  before_script:
    - export IMAGE=$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - export WEB_IMAGE=$IMAGE:web
    - export DB_IMAGE=$IMAGE:db
  script:
    - apk add --no-cache bash
    - chmod +x ./setup_env.sh
    - bash ./setup_env.sh
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:web || true
    - docker pull $IMAGE:db
    - docker-compose -f docker-compose.yml build

    #failed here
    - docker push $IMAGE:web
    - docker push $IMAGE:db


###notes
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#  tagging images: $CI_COMMIT_SHA