version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    command: gunicorn --chdir /usr/src/app/django_developer_portfolio --bind 0.0.0.0:8000 django_developer_portfolio.wsgi:application 
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: