version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.web
    command: gunicorn --chdir /usr/src/app/django_developer_portfolio/ django_developer_portfolio.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - .:/usr/src/app
      - ./django_developer_portfolio/staticfiles:/usr/src/app/django_developer_portfolio/staticfiles
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  nginx:
    build: ./nginx
    volumes:
      - .:/usr/src/app
      - ./django_developer_portfolio/staticfiles:/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data: