version: '3.7'

services:
  web:
    build: ./django-developer-portfolio
    command: python ./django_developer_portfolio/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-developer-portfolio/:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=foo